//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDocumentExplorer.UserControls.FindReplaceControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XDocumentExplorer.UserControls.FindReplaceControl.ControlTexts", typeof(ControlTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string CaseSensitiveButton {
            get {
                return ResourceManager.GetString("CaseSensitiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fi_nd what:.
        /// </summary>
        internal static string FindLabel {
            get {
                return ResourceManager.GetString("FindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        internal static string FindNextButton {
            get {
                return ResourceManager.GetString("FindNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find previous.
        /// </summary>
        internal static string FindPreviousButton {
            get {
                return ResourceManager.GetString("FindPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term.
        /// </summary>
        internal static string FindText {
            get {
                return ResourceManager.GetString("FindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expression.
        /// </summary>
        internal static string RegExButton {
            get {
                return ResourceManager.GetString("RegExButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        internal static string ReplaceAllButton {
            get {
                return ResourceManager.GetString("ReplaceAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re_place with:.
        /// </summary>
        internal static string ReplaceLabel {
            get {
                return ResourceManager.GetString("ReplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace next.
        /// </summary>
        internal static string ReplaceNextButton {
            get {
                return ResourceManager.GetString("ReplaceNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement term.
        /// </summary>
        internal static string ReplaceText {
            get {
                return ResourceManager.GetString("ReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        internal static string WholeWordButton {
            get {
                return ResourceManager.GetString("WholeWordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue at beginning when reaching end of text.
        /// </summary>
        internal static string WrapButton {
            get {
                return ResourceManager.GetString("WrapButton", resourceCulture);
            }
        }
    }
}
