//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDocumentExplorer.WpfWindows.OptionsWindow {
    using System;


    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlTexts {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlTexts() {
        }

        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XDocumentExplorer.WpfWindows.OptionsWindow.ControlTexts", typeof(ControlTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use enhanced XML _Writer: ähnelt.
        /// </summary>
        internal static string EnhWriter {
            get {
                return ResourceManager.GetString("EnhWriter", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If this checkbox is checked, the enhanced XmlWriter developed by Axel Dahmen will be used for writing XDocument\nobject content to the XML output panel. If unchecked, the Microsoft .NET XmlWriter will be used.\n\nThe Microsoft .NET XmlWriter lacks correct formatting of &quot;&quot;xml:space=preserve&quot; content. The enhanced XmlWriter\ndeveloped by Axel Dahmen fixes this but but will only be applied in other programs if they use the corresponding\n&quot;AxDa.EnhancedXmlWriter&quot; NuGet package. ähnelt.
        /// </summary>
        internal static string EnhWriterInfo {
            get {
                return ResourceManager.GetString("EnhWriterInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the maximum number of files that will be dispayed in the Recently Used sub menu.\nYou can enter a minimum of 1 and a maximum of 10 items to be displayed. ähnelt.
        /// </summary>
        internal static string MruCapacityInfo {
            get {
                return ResourceManager.GetString("MruCapacityInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Recently used files capacity: ähnelt.
        /// </summary>
        internal static string MruFileCapacity {
            get {
                return ResourceManager.GetString("MruFileCapacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string OptionsWin {
            get {
                return ResourceManager.GetString("OptionsWin", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace _tab characters in text: ähnelt.
        /// </summary>
        internal static string ReplaceTabs {
            get {
                return ResourceManager.GetString("ReplaceTabs", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If this checkbox is checked, tab characters in the text input control will be replaced by a number of spaces specified by the Tab Size property value.\nMoreover, when opening an existing file, tabs in the text will also be replaced with spaces.\nThe text file content, however, will not be marked as being modified then, so closing unmodified text content will not cause the file to be touched. ähnelt.
        /// </summary>
        internal static string ReplaceTabsInfo {
            get {
                return ResourceManager.GetString("ReplaceTabsInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab _size: ähnelt.
        /// </summary>
        internal static string TabSize {
            get {
                return ResourceManager.GetString("TabSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the number of spaces to be used for replacing a tab character.\nChanging this value does not change the number of existing spaces in the text input control. ähnelt.
        /// </summary>
        internal static string TabSizeInfo {
            get {
                return ResourceManager.GetString("TabSizeInfo", resourceCulture);
            }
        }
    }
}
