//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDocumentExplorer.WpfWindows.MainWindow {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuItems() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XDocumentExplorer.WpfWindows.MainWindow.MenuItems", typeof(MenuItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit ähnelt.
        /// </summary>
        internal static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Copy ähnelt.
        /// </summary>
        internal static string EditMenuCopy {
            get {
                return ResourceManager.GetString("EditMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cu_t ähnelt.
        /// </summary>
        internal static string EditMenuCut {
            get {
                return ResourceManager.GetString("EditMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Find ähnelt.
        /// </summary>
        internal static string EditMenuFind {
            get {
                return ResourceManager.GetString("EditMenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find _Next ähnelt.
        /// </summary>
        internal static string EditMenuFindNext {
            get {
                return ResourceManager.GetString("EditMenuFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find Pre_vious ähnelt.
        /// </summary>
        internal static string EditMenuFindPrevious {
            get {
                return ResourceManager.GetString("EditMenuFindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Paste ähnelt.
        /// </summary>
        internal static string EditMenuPaste {
            get {
                return ResourceManager.GetString("EditMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Replace ähnelt.
        /// </summary>
        internal static string EditMenuReplace {
            get {
                return ResourceManager.GetString("EditMenuReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New ähnelt.
        /// </summary>
        internal static string FileMenuNew {
            get {
                return ResourceManager.GetString("FileMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Open… ähnelt.
        /// </summary>
        internal static string FileMenuOpen {
            get {
                return ResourceManager.GetString("FileMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Quit ähnelt.
        /// </summary>
        internal static string FileMenuQuit {
            get {
                return ResourceManager.GetString("FileMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Recent Files ähnelt.
        /// </summary>
        internal static string FileMenuRecent {
            get {
                return ResourceManager.GetString("FileMenuRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Save ähnelt.
        /// </summary>
        internal static string FileMenuSave {
            get {
                return ResourceManager.GetString("FileMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save _As… ähnelt.
        /// </summary>
        internal static string FileMenuSaveAs {
            get {
                return ResourceManager.GetString("FileMenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _About XDocument Explorer ähnelt.
        /// </summary>
        internal static string HelpMenuAbout {
            get {
                return ResourceManager.GetString("HelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Tools ähnelt.
        /// </summary>
        internal static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Options ähnelt.
        /// </summary>
        internal static string ToolsMenuOptions {
            get {
                return ResourceManager.GetString("ToolsMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _View ähnelt.
        /// </summary>
        internal static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go To _Text Input Box ähnelt.
        /// </summary>
        internal static string ViewMenuFocusTextBox {
            get {
                return ResourceManager.GetString("ViewMenuFocusTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XDocument Formatting Options ähnelt.
        /// </summary>
        internal static string ViewMenuOptions {
            get {
                return ResourceManager.GetString("ViewMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Control Characters ähnelt.
        /// </summary>
        internal static string ViewMenuOptionsEscapeChars {
            get {
                return ResourceManager.GetString("ViewMenuOptionsEscapeChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Omit Duplicate Namespaces ähnelt.
        /// </summary>
        internal static string ViewMenuOptionsNoDuplicate {
            get {
                return ResourceManager.GetString("ViewMenuOptionsNoDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Formatting ähnelt.
        /// </summary>
        internal static string ViewMenuOptionsNoFormat {
            get {
                return ResourceManager.GetString("ViewMenuOptionsNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Show Blank Characters ähnelt.
        /// </summary>
        internal static string ViewMenuShowBlanks {
            get {
                return ResourceManager.GetString("ViewMenuShowBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show XDocu_ment XML Output ähnelt.
        /// </summary>
        internal static string ViewMenuShowXmlOutput {
            get {
                return ResourceManager.GetString("ViewMenuShowXmlOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use LIN_Q to XML ähnelt.
        /// </summary>
        internal static string ViewMenuUseCode {
            get {
                return ResourceManager.GetString("ViewMenuUseCode", resourceCulture);
            }
        }
    }
}
